# Generated by Django 3.0.5 on 2020-06-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('last_login', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SitePassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.TextField()),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('tele_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser')),
            ],
        ),
    ]
